# Generated by Django 5.2.8 on 2025-11-30 15:49

import detection.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HairScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=detection.models.upload_scan_path)),
                ('result', models.CharField(blank=True, choices=[('alopecia', 'Alopecia'), ('dandruff', 'Dandruff'), ('normal', 'Normal')], max_length=20, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hair_scans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
